### ISSUE TITLE
Some violations of CodeReviewComments

### ISSUE THREAD

**Issue by spy16** [sagikazarmark/modern-go-application#16]
1. Repeatation 
   - Package `helloworld` contains a function `NewHelloWorld`.
   - So the client would initialize the `HelloWorld` type as `helloworld.NewHelloWorld` which is simply repeatation of the fact that `helloworld` package contains a `HelloWorld` and is not recommended [Package Names](https://github.com/golang/go/wiki/CodeReviewComments#package-names)
   - This should instead be `helloworld.New()`
2. Interfaces
   - Package `helloworld` contains an interface `HelloWorld` and function `NewHelloWorld` returns this interface type instead of concrete type. Interfaces on implementor side as an abstraction has no meaning
   - Package `helloworld` should contain a concrete type `HelloWorld` which is returned by `helloworld.New` function as recommended [here](https://github.com/golang/go/wiki/CodeReviewComments#interfaces)
   - Clients who need to use features of `HelloWorld` type can define interfaces with only the features they really need and inject instance of `HelloWorld` as an implementation.

**Comment by sagikazarmark** [comment]
> So if a presentation layer (e.g. REST API for `HelloWorld`) requires to use a domain entity

Actually, it's not that simple. Although there is nothing that permits doing that, it's a bad practice to use the domain entity outside of the use case layer.

> In this particular project, only external component helloworld has is the logger and is being imported from go-kit directly which actually violates Clean Code

While this may be technically true, it is not practical **not** to import the go-kit logger here. The package provides a number of helpers which are used by the implementations (like `level` package). Building a full boundary around the logger would require a large amount of code for literally no advantage. The go-kit logger package/interface is quite small and stable, so I'm comfortable with importing it. This is where common sense should be applied IMHO.

> In other words, this particular recommendation for interfaces does not really violate Clean Code in anyway. It actually enforces it.

Sure, my problem is rather with the struct exporting.

> Also, interfaces recommendation reduces decoupling. If `helloworlddriver` had defined an interface `HelloWorld` and `helloworld` package had a concrete type `DefaultHelloWorld` then

I tend to avoid the word `default` in names: it does not mean anything, doesn't help understand what the thing is.

> `helloworlddriver` package is also independent of `helloworld` package

Actually, this isn't true. Even if the interface is defined in the driver package, it still depends on the interfaces and structs defined in the use case package.

> About invalid initialization of unexported fields: this was a concern for me as well.

I wish Go had a tool to enforce initialization compile time, otherwise this is always going to be a risk. The worst thing is that preventing this error to affect you requires full e2e tests, because it only causes issues runtime.

**Comment by spy16** [comment]
> Actually, it's not that simple. Although there is nothing that permits doing that, it's a bad practice to use the domain entity outside of the use case layer.

I actually meant `Use Case` layer here. Apologies. But the point is, there is no reason not point inward. But **avoiding pointing outward** is the only rule in Clean Architecture.

> While this may be technically true, it is not practical not to import the go-kit logger here.

I agree that this is an opinionated and use-case based decision. 

```go
type Logger interface {
      Debugf(msg string, args ...interface{})
      Infof(msg string, args ...interface{})
      Warnf(msg string, args ...interface{})
      Errorf(msg string, args ...interface{})
       
      // WithFields is for annotated loggers
      WithFields(fields map[string]interface{}) Logger
}
```
I prefer having above interface over importing log package because that way if the log package changes a contract my innermost core layers do not need to change which is the whole point of Clean Architecture (i will still be able to create a wrapper around gokit logger once and inject it everywhere instead of changing code all the different layers. [e.g., since `go-kit/log` is specifically designed for gokit micro-services, what if something changes in this package to incorporate a requirement specific to `gokit` framework.?])

> I tend to avoid the word default in names: it does not mean anything, doesn't help understand what the thing is.

That was just an example name to avoid confusion between `HelloWorld` interface and `HelloWorld` implementation. But same goes for `helloWorld` and `HelloWorld`. :)

> Actually, this isn't true. Even if the interface is defined in the driver package, it still depends on the interfaces and structs defined in the use case package.

That depends. 

> I wish Go had a tool to enforce initialization compile time, otherwise this is always going to be a risk. 

Agreed.

**Comment by spy16** [comment]
Let's say `helloworld` package had 2 clients A and B. Client B requested for a feature called `SayReverse` in addition to already existing `SayHello` feature. You added this to `helloWorld` struct. But since this struct is unexported, client B will still not be able to use the added feature. How do you solve this ?  If you thought you could add `SayReverse` signature to `HelloWorld` interface, you would be violating Interface Segregation Principle  (because, even though,  client A doesn't need the new feature it's going to be forced since it's importing your interface instead of defining an interface matching it's requirements) possibly breaking client A.

**Comment by sagikazarmark** [comment]
Okay, first round is here: #17

**Comment by sagikazarmark** [comment]
Here is round two: #18

**Comment by sagikazarmark** [comment]
I was looking at the Logger interface you posted. Actually I had such interface a while back and I realized why I dropped it in the end:

```
      // WithFields is for annotated loggers
      WithFields(fields map[string]interface{}) Logger
```

Because of this line you either have to have an adapter for each interface or have one single, global interface with a single adapter.

I believe the first option simply isn't worth the effort.

The second option kinda defeats the whole purpose. It can protect you from API changes of third-party libraries but from the interface point of view it's the same. That being said, I might just add that global interface anyway, to separate the application from go-kit, but right now the implicit interface doesn't help anything in this case.

**Comment by sagikazarmark** [comment]
I decided to merge the PR. It looks fine, time will tell if it works well.

Thanks for your comments @spy16 again, I think all of them were addressed!

**Comment by spy16** [comment]
@sagikazarmark thanks for considering the suggestions. 

 I have been planning to setup a sample project myself. My idea was to build a full blown application ( [droplets](github.com/spy16/droplets) ) which could be used as a reference project by gophers.  But wasn't able to actively work on it due to time constraints. So kudos for your effort.

**Comment by sagikazarmark** [comment]
I'm planning to add some more examples alongside the greeting one.

**Comment by sagikazarmark** [comment]
Good idea, created an issue #20 for that

**Comment by spy16** [comment]
Everything from this discussion has been addressed.. closing this.

**Comment by sagikazarmark** [comment]
Thanks again @spy16
